categories:
  支出:
    餐饮:
      - 早午晚餐
      - 水果零食
      - 饮料
      - 买菜原料
    交通:
      - 打车
      - 公共交通
      - 加油充电
      - 停车费
      - 高速费
      - 火车高铁
      - 飞机
    购物:
      - 日用品
      - 家居百货
      - 服饰鞋包
      - 化妆护肤
      - 数码电器
    居家:
      - 美容美发
      - 住宿房租
      - 水电燃气
      - 手机电话
      - 宽带网费
      - 保险费
      - 物业
      - 快递费
    娱乐:
      - 网游电玩
      - 电影
      - KTV
      - 洗浴足浴
      - 休闲
      - 歌舞演出
    教育:
      - 学费
      - 书籍
      - 会员费
      - 咨询
    医疗:
      - 医疗药品
      - 挂号门诊
      - 养生保健
    人情往来:
      - 礼金
      - 请客
      - 孝敬老人
      - 送礼
    其他:
      - 宠物
      - 公益捐赠
      - 手续费
      - 维修

  收入:
    工资薪水: []
    兼职外快: []
    奖金: []
    投资收益: []
    红包: []
    报销: []
    退款: []
    利息收入: []
    二手闲置: []
    生活费: []

  转账:
    转账: []
    信用卡还款: []

  借入:
    向朋友借款: []
    网贷: []
    信用借款: []

  借出:
    借朋友: []
    临时垫付: []

  还款:
    信用卡还款: []
    花呗还款: []
    白条还款: []
    借款归还: []

  收款:
    借款收回: []
    垫付款收回: []

accounts:
  - 招行储蓄卡4985
  - 哈哈哈
